/**
 * Dedicated tools for the most frequent project and task operations. Everything
 * else in the Projects area (sprints, milestones, documents, time tracking,
 * automations, analytics…) goes through the generic operation tools.
 *
 * Project routes need an API key linked to a human actor and the projects:*
 * scopes; writes carry an Idempotency-Key generated by the API client.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'
import { apiRequest, ApiError, assertUuid } from './api.js'
import { error, requireConfirmation, text, type ToolResult } from './result.js'

const uuid = z.string().describe('UUID')
const uuidList = z.array(z.string()).max(50)
const perPage = z.number().int().min(1).max(100).optional().describe('Results per page (1-100)')
const confirm = z.boolean().describe('Must be true after explicit user confirmation')

const taskFields = {
  description: z.string().optional().describe('Task description'),
  priority: z.string().optional().describe('Task priority'),
  type: z.string().optional().describe('Task type, including epic when available'),
  task_status_uuid: z.string().optional().describe('Status UUID (see list_project_statuses)'),
  parent_uuid: z.string().optional().describe('Parent task UUID, for a subtask'),
  epic_uuid: z.string().optional().describe('Epic UUID'),
  due_date: z.string().optional().describe('Due date, YYYY-MM-DD'),
}

export function registerProjectTools(server: McpServer, apiKey: string): void {
  async function call(method: string, path: string, body?: unknown, params?: Record<string, unknown>): Promise<ToolResult> {
    try {
      return text(await apiRequest(apiKey, method, path, body, params))
    } catch (e) {
      if (e instanceof ApiError && e.details) return error(`${e.message}: ${JSON.stringify(e.details)}`)
      return error(e instanceof Error ? e.message : 'Unknown error')
    }
  }

  function task(projectUuid: string, taskUuid?: string): string {
    assertUuid(projectUuid, 'project uuid')
    if (taskUuid === undefined) return `/projects/${projectUuid}/tasks`
    assertUuid(taskUuid, 'task uuid')
    return `/projects/${projectUuid}/tasks/${taskUuid}`
  }

  server.tool(
    'list_projects',
    'List the projects visible to the user linked to the API key.',
    {
      search: z.string().optional().describe('Filter on key, name or description'),
      status: z.string().optional().describe('Exact project status'),
      include_archived: z.boolean().optional().describe('Include archived projects'),
      per_page: perPage,
    },
    { readOnlyHint: true },
    async (params) => call('GET', '/projects', undefined, params),
  )

  server.tool(
    'get_project',
    'Get one project by UUID.',
    { project_uuid: uuid.describe('Project UUID') },
    { readOnlyHint: true },
    async ({ project_uuid }) => {
      assertUuid(project_uuid, 'project uuid')
      return call('GET', `/projects/${project_uuid}`)
    },
  )

  server.tool(
    'list_project_statuses',
    'List the task statuses of a project, in board order. Use their UUIDs to filter or transition tasks.',
    { project_uuid: uuid.describe('Project UUID') },
    { readOnlyHint: true },
    async ({ project_uuid }) => {
      assertUuid(project_uuid, 'project uuid')
      return call('GET', `/projects/${project_uuid}/statuses`)
    },
  )

  server.tool(
    'list_project_tasks',
    'Search and paginate the tasks of a project.',
    {
      project_uuid: uuid.describe('Project UUID'),
      search: z.string().max(255).optional().describe('Text search'),
      status: uuidList.optional().describe('Status UUIDs'),
      assignees: uuidList.optional().describe('Assignee (member) UUIDs'),
      labels: uuidList.optional().describe('Label UUIDs'),
      priorities: z.array(z.string()).optional().describe('Task priorities'),
      type: z.array(z.string()).optional().describe('Task types'),
      epic_id: z.string().optional().describe('Epic UUID'),
      sprint: z.string().optional().describe('Sprint UUID'),
      milestone: z.string().optional().describe('Milestone UUID'),
      due_state: z.enum(['all', 'overdue', 'due_soon', 'no_due', 'has_due']).optional().describe('Due date state'),
      include_archived: z.boolean().optional().describe('Include archived tasks'),
      sort_by: z.string().optional().describe('Sort field'),
      sort_direction: z.enum(['asc', 'desc']).optional().describe('Sort direction'),
      per_page: perPage,
    },
    { readOnlyHint: true },
    async ({ project_uuid, ...params }) => call('GET', task(project_uuid), undefined, params),
  )

  server.tool(
    'get_project_task',
    'Get one task with its relations (status, assignees, labels, parent, epic…).',
    { project_uuid: uuid.describe('Project UUID'), task_uuid: uuid.describe('Task UUID') },
    { readOnlyHint: true },
    async ({ project_uuid, task_uuid }) => call('GET', task(project_uuid, task_uuid)),
  )

  server.tool(
    'create_project_task',
    'Create a task, subtask or epic in a project. Requires confirmation.',
    {
      project_uuid: uuid.describe('Project UUID'),
      title: z.string().min(1).max(255).describe('Task title'),
      ...taskFields,
      confirm,
    },
    async ({ project_uuid, confirm, ...body }) => {
      requireConfirmation(confirm, 'creating a project task')
      return call('POST', task(project_uuid), body)
    },
  )

  server.tool(
    'update_project_task',
    'Update a task and its planning references (sprint, milestone, estimates, custom fields). Use transition_project_task to change only the status. Requires confirmation.',
    {
      project_uuid: uuid.describe('Project UUID'),
      task_uuid: uuid.describe('Task UUID'),
      title: z.string().min(1).max(255).optional().describe('Task title'),
      ...taskFields,
      milestone_uuid: z.string().optional().describe('Milestone UUID'),
      sprint_uuid: z.string().optional().describe('Sprint UUID'),
      estimated_hours: z.number().optional().describe('Estimated hours'),
      story_points: z.number().int().optional().describe('Story points'),
      progress: z.number().int().min(0).max(100).optional().describe('Progress percentage'),
      custom_fields: z.record(z.unknown()).optional().describe('Custom field values by key'),
      change_comment: z.string().max(1000).optional().describe('Reason for a date change'),
      confirm,
    },
    async ({ project_uuid, task_uuid, confirm, ...body }) => {
      requireConfirmation(confirm, 'updating a project task')
      return call('PATCH', task(project_uuid, task_uuid), body)
    },
  )

  server.tool(
    'transition_project_task',
    'Move a task to another status of the same project. Requires confirmation.',
    {
      project_uuid: uuid.describe('Project UUID'),
      task_uuid: uuid.describe('Task UUID'),
      status_uuid: uuid.describe('Target status UUID (see list_project_statuses)'),
      confirm,
    },
    async ({ project_uuid, task_uuid, status_uuid, confirm }) => {
      assertUuid(status_uuid, 'status uuid')
      requireConfirmation(confirm, 'changing a task status')
      return call('POST', `${task(project_uuid, task_uuid)}/transition`, { status_uuid })
    },
  )

  server.tool(
    'list_project_task_comments',
    'List the visible comments of a task.',
    { project_uuid: uuid.describe('Project UUID'), task_uuid: uuid.describe('Task UUID'), per_page: perPage },
    { readOnlyHint: true },
    async ({ project_uuid, task_uuid, per_page }) => call('GET', `${task(project_uuid, task_uuid)}/comments`, undefined, { per_page }),
  )

  server.tool(
    'add_project_task_comment',
    'Add a comment to a task, attributed to the user linked to the API key. Requires confirmation.',
    {
      project_uuid: uuid.describe('Project UUID'),
      task_uuid: uuid.describe('Task UUID'),
      content: z.string().min(1).max(50000).describe('Comment content'),
      confirm,
    },
    async ({ project_uuid, task_uuid, content, confirm }) => {
      requireConfirmation(confirm, 'commenting on a task')
      return call('POST', `${task(project_uuid, task_uuid)}/comments`, { content })
    },
  )
}
